=== brdd3v/git-diff-sql-changes/conf/regex_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "DML": {
      "type": ["array", "string"]
    },
    "Comments": {
      "type": ["array", "string"]
    },
    "Index": {
      "type": ["array", "string"]
    },
    "PK": {
      "type": ["array", "string"]
    },
    "Engine": {
      "type": ["array", "string"]
    },
    "Privilege": {
      "type": ["array", "string"]
    }
  },
  "required": [
    "DML",
    "Comments",
    "Index",
    "PK",
    "Engine",
    "Privilege"
  ]
}

=== brdd3v/git-diff-sql-changes/conf/regex.json
{
  "DML": ["((select\\s+\\S+\\s+from\\s+\\S+)|",
          "(insert\\s+into\\s+\\S+)|",
          "(insert\\s+ignore\\s+into\\s+\\S+)|",
          "(replace\\s+into\\s+\\S+)|",
          "(update\\s+\\S+\\s+set)|",
          "(delete\\s+from\\s+\\S+))"],

  "Comments": "--.*|#.*|(((\\/\\*)+?[\\w\\W]+?(\\*\\/)+))",

  "Index": ["(drop\\s+index)|",
            "(create\\s+index)|",
            "(create\\s+unique\\s+index)"],

  "PK": "primary\\s+key",

  "Engine": ["engine\\s*=\\s*(MyISAM|MERGE|InnoDB|",
             "MEMORY|ARCHIVE|BLACKHOLE|CSV|FEDERATED)"],

  "Privilege": "^(grant|revoke)\\s+\\S+"
}
